package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Application.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Application {
	public static void Main(String[] args) {
	
	}
}
