package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bullet.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Bullet {
	/**
	 * Megadja, hogy mennyivel kell cs�kkenteni sebz�skor az Enemy health v�ltoz�j�t.
	**/
	private int damage;
	
	/**
	 * Megadja annak az ellens�gnek a t�pus�t, amire nagyobb a sebz�s, fejlesztett�k a bulletet. 
	**/
	private Enemy enemyType;
	
	private Tower bullet;
	
	/**
	 * Konstruktor
	 *
	 * @param    dmg
	 * @param    et
	**/
	public void Bullet(int dmg, Enemy et) {
	
	}
	
	/**
	 * Megadja, hogy mennyit sebez a Bullet egy Elf-en.
	**/
	public int getDamageElf() {
		return damage;
	
	}
	
	/**
	 * Megadja, hogy mennyit sebez a Bullet egy Hobbit-on.
	**/
	public int getDamageHobbit() {
		return damage;
	
	}
	
	/**
	 * Megadja, hogy mennyit sebez a Bullet egy Dwarf-on.
	**/
	public int getDamageDwarf() {
		return damage;
	
	}
	
	/**
	 * Megadja, hogy mennyit sebez a Bullet egy Human-en.
	**/
	public int getDamageHuman() {
		return damage;
	
	}
	
	public void setEnemy(Enemy e) {
	
	}
	
	public void setDamage(int dmg) {
	
	}
}
