//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cell.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public abstract class Cell {
	/**
	 * A cella 4 szomszédja.
	**/
	private Array<Cell> neighbours;
	
	private Cell neighbours;
	
	private Map grid;
	
	/**
	 * Konstruktor.
	 *
	 * @param    cells
	**/
	public void Cell(Array<Cell> cells) {
	
	}
	
	/**
	 * Visszatér egy bool értékkel, ami megmondja, hogy az adott mezõ Pathy-e vagy sem.
	**/
	public bool isPath() {
	
	}
}
