package Program.Skeleton;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cell.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public abstract class Cell {
	/**
	 * A cella 4 szomsz�dja.
	**/
	private ArrayList<Cell> neighbours;
	
	// ez miert került ide?
	//private Cell neighbours;
	
	private Map grid;
	
	/**
	 * Konstruktor.
	 *
	 * @param    cells
	**/
	public void Cell(ArrayList<Cell> cells) {
	
	}
	
	/**
	 * Visszat�r egy bool �rt�kkel, ami megmondja, hogy az adott mez� Pathy-e vagy sem.
	**/
	public abstract boolean isPath();
}
