package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DamageGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//

public class DamageGem extends Gem implements ITGem {
	private int damage;
	public void DamageGem() {
	
	}
	
	public void upgradeTower(Tower t) {
	
	}
	
	public int getValue() {
		System.out.println("--> DamageGem getValue");
		System.out.println("<-- DamegeGem return");
		return 0;
	}
}
