package skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DamageGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//

public class DamageGem extends Gem implements ITGem {
	public static final int price = 20;

	private int damage;
	public DamageGem() {
		SkeletonTester.safePrint("--> DamageGem konstruktor", true);

		SkeletonTester.safePrint("<-- DamageGem konstruktor return", false);

	}
	
	public void upgradeTower(Tower t) {
		SkeletonTester.safePrint("--> DamageGem upgradeTower", true);
		t.upgradeDamage(damage);
		
		// TODO hello
		
		SkeletonTester.safePrint("<-- Damagegem upgradeTower return", false);
	}
	
	public int getValue() {
		SkeletonTester.safePrint("--> DamageGem getValue", true);
		
		SkeletonTester.safePrint("<-- DamegeGem return", false);
		return 0;
	}
}
