//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Elf.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




/**
 * Elf típusú Enemy
**/
public class Elf extends Enemy {
	public void eliminate(Path p);
	public void registerPath(Path p);
}
