//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enemy.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




/**
 * A különbözõ ellenségek (Hobbit, Dwarf, Elf, Human) absztrakt õsosztálya.
**/
public abstract class Enemy implements IPathPlaceable {
	/**
	 * Az Enemy normál sebessége.
	**/
	private static final int speed;
	
	/**
	 * Az Enemy módosított sebessége, vagyis a lassítás mértékével megváltoztatott érték.
	**/
	private int modSpeed;
	
	/**
	 * Az Enemy életereje.
	**/
	private int health;
	
	/**
	 * A Path címe, amin az Enemy éppen tartózkodik.
	**/
	private Path myPath;
	
	private IGame igame;
	
	/**
	 * Konstruktor.
	 *
	 * @param    sp
	 * @param    msp
	 * @param    h
	 * @param    ig
	**/
	public void Enemy(int sp, int msp, int h, IGame ig) {
	
	}
	
	/**
	 * A kapott bullet alapján megsebzi az Enemy-t. Minden Enemy-re más a függvénytörzs.
	 *
	 * @param    b
	**/
	public void hurt(Bullet b) {
	
	}
	
	/**
	 * Az Enemy mozgását végrehajtó metódus.
	**/
	public void move() {
	
	}
	
	public void setModSpeed(int msp) {
	
	}
	
	public void eliminate(Path p);
	
	public void registerPath(Path p);
}
