package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enemy.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




/**
 * A k�l�nb�z� ellens�gek (Hobbit, Dwarf, Elf, Human) absztrakt �soszt�lya.
**/
public abstract class Enemy implements IPathPlaceable {
	/**
	 * Az Enemy norm�l sebess�ge.
	**/
	private static final int speed = 10;
	
	/**
	 * Az Enemy m�dos�tott sebess�ge, vagyis a lass�t�s m�rt�k�vel megv�ltoztatott �rt�k.
	**/
	private int modSpeed;
	
	/**
	 * Az Enemy �letereje.
	**/
	private int health;
	
	/**
	 * A Path c�me, amin az Enemy �ppen tart�zkodik.
	**/
	private Path myPath;
	
	private IGame igame;
	
	/**
	 * Konstruktor.
	 *
	 * @param    sp
	 * @param    msp
	 * @param    h
	 * @param    ig
	**/
	public void Enemy(int sp, int msp, int h, IGame ig) {
	
	}
	
	/**
	 * A kapott bullet alapj�n megsebzi az Enemy-t. Minden Enemy-re m�s a f�ggv�nyt�rzs.
	 *
	 * @param    b
	**/
	public void hurt(Bullet b) {
	
	}
	
	/**
	 * Az Enemy mozg�s�t v�grehajt� met�dus.
	**/
	public void move() {
	
	}
	
	public void setModSpeed(int msp) {
	
	}
	
	public void eliminate(Path p) {
	}
	
	public void registerPath(Path p) {
	}
}
