//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Field extends Cell {
	/**
	 * A mezõn lévõ, torony interfészû változó referenciája.
	**/
	private ITower itower;
	
	private IGame igame;
	
	private Tower myField;
	
	/**
	 * Konstruktor
	**/
	public void Field() {
	
	}
	
	/**
	 * Törli a paraméterként kapott IFieldPlaceable interfészû változót a mezõrõl. 
	 *
	 * @param    ifp
	**/
	public bool deleteIFieldPlaceable(IFieldPlaceable ifp) {
	
	}
	
	/**
	 * Beregisztrálja a kapott IFieldPlaceable interfészû változót a mezõn.
	 *
	 * @param    ifp
	**/
	public void registerIFieldPlaceable(IFieldPlaceable ifp) {
	
	}
	
	/**
	 * Beregisztrálja a torony interfészû változót a mezõn.
	 *
	 * @param    it
	**/
	public void registerITower(ITower it) {
	
	}
}
