//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Field.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Field extends Cell {
	/**
	 * A mez�n l�v�, torony interf�sz� v�ltoz� referenci�ja.
	**/
	private ITower itower;
	
	private IGame igame;
	
	private Tower myField;
	
	/**
	 * Konstruktor
	**/
	public void Field() {
	
	}
	
	/**
	 * T�rli a param�terk�nt kapott IFieldPlaceable interf�sz� v�ltoz�t a mez�r�l. 
	 *
	 * @param    ifp
	**/
	public bool deleteIFieldPlaceable(IFieldPlaceable ifp) {
	
	}
	
	/**
	 * Beregisztr�lja a kapott IFieldPlaceable interf�sz� v�ltoz�t a mez�n.
	 *
	 * @param    ifp
	**/
	public void registerIFieldPlaceable(IFieldPlaceable ifp) {
	
	}
	
	/**
	 * Beregisztr�lja a torony interf�sz� v�ltoz�t a mez�n.
	 *
	 * @param    it
	**/
	public void registerITower(ITower it) {
	
	}
	
	public boolean isPath(){
	  return false;
	}
}
