//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Game implements IGame {
	/**
	 * A térkép, amiben a cellák tárolódnak.
	**/
	private Map map;
	
	/**
	 * Az ellenségek listája, akik az adott pályára belépnek.
	**/
	private ArrayList<Enemy> enemiesIn;
	
	private ArrayList<Enemy> enemiesOut;
	
	private ArrayList<Tower> towers;
	
	/**
	 * A játékos varázsereje, amibõl akadályokat, tornyokat vehet, ill. ami minden megölt ellenség után gyarapszik.
	**/
	private int mana;
	
	private Path firstP;
	
	private int noEnemies;
	
	private int succeededE;
	
	/**
	 * Konstruktor
	**/
	public void Game() {
	
	}
	
	/**
	 * Frissíti a GUI-t.
	**/
	public void update() {
	
	}
	
	public void makeEnemies() {
	
	}
	
	public void initialize(String name) {
	
	}
	
	/**
	 * A manát csökkentõ/jóváíró függvény.
	**/
	public void changeMana();
	
	public void incSucceeded();
	
	public void addTower(Tower t);
	
	public void removeTower(Tower t);
	
	public void removeEnemy(Enemy e);
}
