//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public abstract class Gem {
	/**
	 * A kristály ára. Statikus, mert minden kristály ugyanannyiba kerül.
	**/
	private int price;
	
	/**
	 * Konstruktor
	 *
	 * @param    price
	**/
	public void Gem(int price) {
	
	}
}
