package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public abstract class Gem {
	/**
	 * A krist�ly �ra. Statikus, mert minden krist�ly ugyanannyiba ker�l.
	**/
	public static int price = 10;
	
	/**
	 * Konstruktor
	 *
	 * @param    price
	**/
	public Gem() {
	
	}
}
