//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hobbit.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




/**
 * Hobbit típusú Enemy
**/
public class Hobbit extends Enemy {
	public void eliminate(Path p);
	public void registerPath(Path p);
}
