package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hobbit.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




/**
 * Hobbit t�pus� Enemy
**/
public class Hobbit extends Enemy {
	public void eliminate(Path p) {
	}
	public void registerPath(Path p) {
	}
	@Override
	public void hurt(Bullet b) {
		SkeletonTester.safePrint("--> Hobbit hurt", true);
		
		b.getDamageHobbit();

		SkeletonTester.safePrint("<-- Hobbit hurt return", false);		
	}
}
