//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IGame.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public interface IGame {
	/**
	 * A manát csökkentõ/jóváíró függvény.
	**/
	public void changeMana();
	
	public void incSucceeded();
	
	public void addTower(Tower t);
	
	public void removeTower(Tower t);
	
	public void removeEnemy(Enemy e);
}
