package skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IGame.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public interface IGame {
	/**
	 * A man�t cs�kkent�/j�v��r� f�ggv�ny.
	**/
	public void changeMana(int value);
	
	public int getMana();
	
	public void incSucceeded();
	
	public void addTower(Tower t);
	
	public void removeTower(Tower t);
	
	public void removeEnemy(Enemy e);
}
