package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IntensityGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class IntensityGem extends Gem implements IOGem {
	private int intestity;
	public void IntensityGem() {
	
	}
	
	public void upgradeObstacle(Obstacle o) {
	}
}
