package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IOGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public interface IOGem {
	public void upgradeObstacle(Obstacle o);
}
