//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IPathPlaceable.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public interface IPathPlaceable {
	public void eliminate(Path p);
	public void registerPath(Path p);
}
