package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ITGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public interface ITGem {
	public void upgradeTower(Tower t);
	public int getValue();
}
