//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Map {
	/**
	 * A pálya neve.
	**/
	private String name;
	
	/**
	 * A pálya szintje
	**/
	private int level;
	
	/**
	 * Maga a játék térképe Tartalmazza a cellákat.
	**/
	private ArrayList<ArrayList<Cell>> grid;
	
	private Game map;
	
	/**
	 * Konstruktor
	 *
	 * @param    name
	**/
	public void Map(String name) {
	
	}
	
	/**
	 * Betölti a következõ pályát.
	 *
	 * @param    name
	**/
	public void load(String name) {
	
	}
	
	public int getLevel() {
	
	}
	
	public String getName() {
	
	}
	
	public Path getFirstPath() {
	
	}
}
