package Program.Skeleton;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Map {
	/**
	 * A p�lya neve.
	**/
	private String name;
	
	/**
	 * A p�lya szintje
	**/
	private int level;
	
	/**
	 * Maga a j�t�k t�rk�pe Tartalmazza a cell�kat.
	**/
	private ArrayList<ArrayList<Cell>> grid;
	
	private Game game;
	
	/**
	 * Konstruktor
	 *
	 * @param    name
	**/
	public Map(Game game) {
		SkeletonTester.safePrint("--> Map konstruktor", true);
		Field f = new Field(game);
		Path p = new Path();
		SkeletonTester.safePrint("<-- Map konstruktor return", false);
	}
	
	/**
	 * Bet�lti a k�vetkez� p�ly�t.
	 *
	 * @param    name
	**/
	public void load(String name) {
		SkeletonTester.safePrint("--> Map load", true);
		
		
		
		SkeletonTester.safePrint("<-- Map load return", false);
	}
	
	public int getLevel() {
		return level;
	
	}
	
	public String getName() {
		return name;
	
	}
	
	public Path getFirstPath() {
		return null;
	
	}
}
