package Program.Skeleton;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Obstacle.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Obstacle implements IObstacle, IPathPlaceable {
	/**
	 * Az akad�ly �ra. Statikus, mert minden akad�lyra ugyanannyi.
	**/
	public static final int price = 10;
	
	/**
	 * A lass�t�s m�rt�ke.
	**/
	private int slowIntens;
	
	/**
	 * Az amortiz�ci� m�rt�ke.
	**/
	private int amort;
	
	/**
	 * Az Path c�me, amin az akad�ly van.
	**/
	private Path myPath;
	
	private ArrayList<IOGem> gems;
	
	/**
	 * Konstruktor
	 *
	 * @param    price
	 * @param    intens
	 * @param    am
	 * @param    p
	 * @param    up
	**/
	public Obstacle() {
		SkeletonTester.safePrint("--> Obstacle konstruktor", true);
		
		SkeletonTester.safePrint("<-- Obstacle konstruktor return", false);
	
	}
	
	public void slow(Enemy e) {
	}
	
	public void amortization() {
	}
	
	public void increaseIntensity(int intens) {
	}
	
	public void addIOGem(IOGem g) {
	}
	
	public void repair() {
	}
	
	public void eliminate(Path p) {
	}
	
	public void registerPath(Path p) {
		SkeletonTester.safePrint("--> Obstacle registerPath", true);
		myPath = p;
		
		p.registerIObstacle(this);
		
		SkeletonTester.safePrint("<-- Obstacle registerPath return", false);
	
	}
}
