//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Obstacle.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Obstacle implements IObstacle, IPathPlaceable {
	/**
	 * Az akadály ára. Statikus, mert minden akadályra ugyanannyi.
	**/
	private static final int price;
	
	/**
	 * A lassítás mértéke.
	**/
	private int slowIntens;
	
	/**
	 * Az amortizáció mértéke.
	**/
	private int amort;
	
	/**
	 * Az Path címe, amin az akadály van.
	**/
	private Path myPath;
	
	private ArrayList<IOGem> gems;
	
	/**
	 * Konstruktor
	 *
	 * @param    price
	 * @param    intens
	 * @param    am
	 * @param    p
	 * @param    up
	**/
	public void Obstacle(int price, int intens, int am, Path p, bool up) {
	
	}
	
	public void slow(Enemy e);
	
	public void amortization();
	
	public void increaseIntensity(int intens);
	
	public void addIOGem(IOGem g);
	
	public void repair();
	
	public void eliminate(Path p);
	
	public void registerPath(Path p);
}
