package Program.Skeleton;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RangeGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class RangeGem extends Gem implements ITGem {
	private int range;
	public void RangeGem() {
	
	}
	
	public void upgradeTower(Tower t) {
	}
	
	public int getValue() {
		return 0;
	}
}
