//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SpeedGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class SpeedGem extends Gem implements ITGem {
	private int speed;
	public void SpeedGem() {
	
	}
	
	public void upgradeTower(Tower t);
	
	public int getValue();
}
