package Program.Skeleton;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tower.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//


public class Tower implements ITower, IFieldPlaceable {
	/**
	 * A torony �ra. Az az �rt�k, amit a man�b�l le kell vonni ahhoz, hogy a j�t�kos megvehesse a tornyot. Statikus, mert minden toronyra ugyanaz.
	**/
	private static final int price = 10;
	
	/**
	 * A torony hat�sugara, hogy h�ny cell�t �r el a szomsz�dos cell�k k�z�l.
	**/
	private int range;
	private int speedCtr;
	private int speed;
	/**
	 * A l�ved�k amit a torony kil�.
	**/
	private Bullet bullet;
	
	/**
	 * Fejleszt�seket t�rol� v�ltoz�. Ebb�l der�l ki, hogy az adott toronyra milyen Gem-eket vett m�r meg a j�t�kos.
	**/
	private ArrayList<ITGem> gems;
	
	/**
	 * Annak a mez�nek a referenci�ja, amelyiken az adott torony �ll.
	**/
	private Field myField;
	
	/**
	 * Azon cell�k list�ja, amelyek beleesnek a l�t�vba (range).
	**/
	private ArrayList<Path> paths;
	private IGame igame;
	private Field itower;
	public Game towers;
	
	/**
	 * Konstruktor
	 *
	 * @param    rang
	 * @param    pr
	**/
	public Tower(IGame game, Field field) {
		igame = game;
		myField = field;
//		System.out.println("--> Tower konstruktor");
//		System.out.println("<-- Tower return");
	}
	
	public void upgradeSpeed(int sp) {
	
	}
	
	public void upgradeRange(int rng) {
	
	}
	
	public void upgradeEnemy(Enemy e) {
	
	}
	
	public void upgradeDamage(int dmg) {
	
	}
	
	public Enemy chooseEnemy() {
		System.out.println("--> Tower choose enemy");
		
		System.out.println("<-- Tower return");		
		return null;
	}
	
	// kivalaszt egy ellenseget es megsebzi a bullet-tel
	public void shoot() {
		System.out.println("--> Tower shoot");

		Enemy target = chooseEnemy();
		
		target.hurt(bullet);
		System.out.println("<-- Tower return");
	}
	
	public void setPaths() {
		System.out.println("--> Tower setPaths");
		
		System.out.println("<-- Tower return");
	}
	
	public void addITGem(ITGem g) {
		System.out.println("--> Tower");
		gems.add(g);
		System.out.println("<-- Tower return");
	}
	
	public void registerField(Field field) {
		myField = field;
	}
	
	public void sell() {
		System.out.println("--> Tower sell");
		int value = price/2;
		
		
		for(ITGem g:gems){
			value = g.getValue();
		}
		
		System.out.print('\t');
		igame.changeMana(value);
		System.out.print('\t');
		igame.removeTower(this);
		System.out.print('\t');
		myField.deleteIFieldPlaceable(this);
		System.out.println("<-- Tower return");
	}
}
