//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tower.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Tower implements ITower, IFieldPlaceable {
	/**
	 * A torony ára. Az az érték, amit a manából le kell vonni ahhoz, hogy a játékos megvehesse a tornyot. Statikus, mert minden toronyra ugyanaz.
	**/
	private static final int price;
	
	/**
	 * A torony hatósugara, hogy hány cellát ér el a szomszédos cellák közül.
	**/
	private int range;
	
	private int speedCtr;
	
	private int speed;
	
	/**
	 * A lövedék amit a torony kilõ.
	**/
	private Bullet bullet;
	
	/**
	 * Fejlesztéseket tároló változó. Ebbõl derül ki, hogy az adott toronyra milyen Gem-eket vett már meg a játékos.
	**/
	private ArrayList<ITGem> gems;
	
	/**
	 * Annak a mezõnek a referenciája, amelyiken az adott torony áll.
	**/
	private Field myField;
	
	/**
	 * Azon cellák listája, amelyek beleesnek a lõtávba (range).
	**/
	private ArrayList<Path> paths;
	
	private IGame igame;
	
	private Field itower;
	
	public Game towers;
	
	/**
	 * Konstruktor
	 *
	 * @param    rang
	 * @param    pr
	**/
	public void Tower(int rang, int pr) {
	
	}
	
	public void upgradeSpeed(int sp) {
	
	}
	
	public void upgradeRange(int rng) {
	
	}
	
	public void upgradeEnemy(Enemy e) {
	
	}
	
	public void upgradeDamage(int dmg) {
	
	}
	
	public Enemy chooseEnemy();
	
	public void shoot();
	
	public void setPaths();
	
	public void addITGem(ITGem g);
	
	public void registerField(Field field);
	
	public void sell();
}
