package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Application.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//


public class Application {
	
	
	public void Initialize(){
		ProtoTester.safePrint("--> Application Initialize", true);
		Game game = new Game();
		game.initialize("MapName");
		
		ProtoTester.safePrint("<-- Application Initialize return", false);
	}

}
