package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bullet.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class Bullet {
	/**
	 * Megadja, hogy mennyivel kell cs�kkenteni sebz�skor az Enemy health v�ltoz�j�t.
	**/
	private int damage = 10;
	
	/**
	 * Megadja annak az ellens�gnek a t�pus�t, amire nagyobb a sebz�s, fejlesztett�k a bulletet. 
	**/
	private String enemyType;
	
	// WTF??
	private Tower bullet;
	
	/**
	 * Konstruktor
	 *
	 * @param    dmg
	 * @param    et
	**/
	public Bullet() {

	}
	
	/**
	 * Megadja, hogy mennyit sebez a Bullet egy Elf-en.
	**/
	public int getDamageElf() {
		ProtoTester.safePrint("--> Bullet getDamageElf", true);

		ProtoTester.safePrint("<-- Bullet getDamageElf return", false);
		return damage;
	
	}
	
	/**
	 * Megadja, hogy mennyit sebez a Bullet egy Hobbit-on.
	**/
	public int getDamageHobbit() {
		ProtoTester.safePrint("--> Bullet getDamageHobbit", true);

		ProtoTester.safePrint("<-- Bullet getDamageHobbit return", false);
		return damage;
	
	}
	
	/**
	 * Megadja, hogy mennyit sebez a Bullet egy Dwarf-on.
	**/
	public int getDamageDwarf() {
		ProtoTester.safePrint("--> Bullet getDamageDwarf", true);

		ProtoTester.safePrint("<-- Bullet getDamageDwarf return", false);
		return damage;
	
	}
	
	/**
	 * Megadja, hogy mennyit sebez a Bullet egy Human-en.
	**/
	public int getDamageHuman() {
		ProtoTester.safePrint("--> Bullet getDamageHuman", true);

		ProtoTester.safePrint("<-- Bullet getDamageHuman return", false);
		return damage;
	
	}
	
	public void setEnemy(String e) {
		ProtoTester.safePrint("--> Bullet setEnemy", true);

		ProtoTester.safePrint("<-- Bullet setEnemy return", false);
	}
	
	public void setDamage(int dmg) {
		ProtoTester.safePrint("--> Bullet setDamage", true);

		ProtoTester.safePrint("<-- Bullet setDamage return", false);
	}
}
