package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EnemyTypeGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//


public class EnemyTypeGem extends Gem implements ITGem {
	public static final int price = 20;

	private String eType;
	public EnemyTypeGem(String enemyType) {
		ProtoTester.safePrint("--> EnemyType konstruktor", true);
		eType = enemyType;
		ProtoTester.safePrint("<-- EnemyType konstruktor return", false);
	}
	
	public void upgradeTower(Tower t) {
		ProtoTester.safePrint("--> EnemyTypeGem upgradeTower", true);
		t.upgradeEnemy(eType);
		ProtoTester.safePrint("<-- EnemyTypeGem upgradeTower return",false);
	}
	
	public int getValue() {
		return 0;
	}
}
