package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Enemy.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//

/**
 * A k�l�nb�z� ellens�gek (Hobbit, Dwarf, Elf, Human) absztrakt �soszt�lya.
**/
public abstract class Enemy implements IPathPlaceable {
	/**
	 * Az Enemy norm�l sebess�ge.
	**/
	private static final int speed = 10;
	private static final int maxHP = 100;

	/**
	 * Az Enemy m�dos�tott sebess�ge, vagyis a lass�t�s m�rt�k�vel megv�ltoztatott �rt�k.
	**/
	private int modSpeed;
	
	/**
	 * Az Enemy �letereje.
	**/
	protected int health;
	
	/**
	 * A Path c�me, amin az Enemy �ppen tart�zkodik.
	**/
	protected Path myPath;
	private Path nextPath;
	
	protected IGame igame;
	
	/**
	 * Konstruktor.
	 *
	 * @param    sp
	 * @param    msp
	 * @param    h
	 * @param    ig
	**/
	public Enemy(IGame game, Path p) {
		ProtoTester.addToObjectCatalog(this);
		igame = game;
		health = maxHP;
		myPath = p;
	}
	
	/**
	 * A kapott bullet alapj�n megsebzi az Enemy-t. Minden Enemy-re m�s a f�ggv�nyt�rzs.
	 *
	 * @param    b
	**/
	public abstract void hurt(Bullet b);
	
	/**
	 * Az Enemy mozg�s�t v�grehajt� met�dus.
	**/
	public void move() {
		
		nextPath = myPath.getNext();
		
		if(nextPath== null){
			igame.incSucceeded();
			eliminate(myPath);
		}else{		
			nextPath.registerIPathPlaceable(this);
		}
		
	}
	
	public void setModSpeed(int msp) {
	
	}
	
	public void eliminate(Path p) {
	}
	
	public void registerPath(Path p) {
		
		
		myPath.deleteEnemy(this);
		
		nextPath.registerEnemy(this);
		
	}
	
	public void setHealth(int hp){
		health = hp;		
	}
}
