package proto;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//

public class Game implements IGame {
	public static boolean bRandom = false;
	/**
	 * A t�rk�p, amiben a cell�k t�rol�dnak.
	**/
	private Map map;
	
	/**
	 * Az ellens�gek list�ja, akik az adott p�ly�ra bel�pnek.
	**/
	private ArrayList<Enemy> enemiesIn;
	
	private ArrayList<Enemy> enemiesOut;
	
	private ArrayList<Tower> towers;
	
	/**
	 * A j�t�kos var�zsereje, amib�l akad�lyokat, tornyokat vehet, ill. ami minden meg�lt ellens�g ut�n gyarapszik.
	**/
	private int mana;
	
	private Path firstP;
	
	private int noEnemies;
	
	private int succeededE;
	
	/**
	 * Konstruktor
	**/
	public Game() {
		ProtoTester.safePrint("--> Game konstruktor", true);
		
		enemiesIn = new ArrayList<Enemy>();
		enemiesOut = new ArrayList<Enemy>();
		towers = new ArrayList<Tower>();
		
		map = new Map(null);
		
		ProtoTester.safePrint("<-- Game konstruktor return", false);
	}
	
	/**
	 * Friss�ti a GUI-t.
	**/
	public void update() {
		ProtoTester.safePrint("update", true);
		ProtoTester.safePrint("update return", false);

	}
	
	public void makeEnemies() {
	
	}
	
	public void initialize(String name) {
		ProtoTester.safePrint("--> Game initialize", true);
		map.load(name);
		ProtoTester.safePrint("<-- Game initialize return", false);	
	}
	
	/**
	 * A man�t cs�kkent�/j�v��r� f�ggv�ny.
	**/
	public void changeMana(int value) {
		ProtoTester.safePrint("--> Game changeMana", true);
		mana += value;
		ProtoTester.safePrint("<-- Game changeMana return", false);
	}
	
	public void incSucceeded() {
		ProtoTester.safePrint("--> Game incSucceeded", true);
		
		ProtoTester.safePrint("<-- Game incSucceeded", false);
	}
	
	public void addTower(Tower t) {
		ProtoTester.safePrint("--> Game addTower", true);
		
		if(towers != null){
			towers.add(t);
		}
		
		ProtoTester.safePrint("<-- Game addTower return", false);
	}
	
	public void removeTower(Tower t) {
		ProtoTester.safePrint("--> Game removeTower", true);
		
		ProtoTester.safePrint("<-- Game removeTower return", false);
	}
	
	public void removeEnemy(Enemy e) {
		ProtoTester.safePrint("--> Game removeEnemy", true);
		
		ProtoTester.safePrint("<-- Game removeEnemy return", false);
	}

	@Override
	public int getMana() {
		ProtoTester.safePrint("--> Game getMana", true);
		
		ProtoTester.safePrint("<-- Game getMana return", false);
		return mana;
	}

	public Map getMap(){
		return map;
	}
}
