package proto;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//

public class Game implements IGame {
	public static boolean bRandom = false;
	/**
	 * A t�rk�p, amiben a cell�k t�rol�dnak.
	**/
	private Map map;
	
	/**
	 * Az ellens�gek list�ja, akik az adott p�ly�ra bel�pnek.
	**/
	private ArrayList<Enemy> enemiesIn;
	
	private ArrayList<Enemy> enemiesOut;
	
	private ArrayList<Tower> towers;
	
	/**
	 * A j�t�kos var�zsereje, amib�l akad�lyokat, tornyokat vehet, ill. ami minden meg�lt ellens�g ut�n gyarapszik.
	**/
	private int mana;
	
	private Path firstP;
	
	private int noEnemies;
	
	private int succeededE;
	
	/**
	 * Konstruktor
	**/
	public Game() {		
		enemiesIn = new ArrayList<Enemy>();
		enemiesOut = new ArrayList<Enemy>();
		towers = new ArrayList<Tower>();
		
		map = new Map(null);
	}
	
	/**
	 * Friss�ti a GUI-t.
	**/
	public void update() {
		ProtoTester.safePrint("update", true);
		
		ProtoTester.safePrint("update return", false);
	}
	
	public void makeEnemies() {
	
	}
	
	public void initialize(String name) {
		map.load(name);
	}
	
	/**
	 * A man�t cs�kkent�/j�v��r� f�ggv�ny.
	**/
	public void changeMana(int value) {
		mana += value;
	}
	
	public void incSucceeded() {
	}
	
	public void addTower(Tower t) {
		
		if(towers != null){
			towers.add(t);
		}
		
	}
	
	public void removeTower(Tower t) {
	
	}
	
	public void removeEnemy(Enemy e) {
	
	}

	@Override
	public int getMana() {
		
		return mana;
	}

	public Map getMap(){
		return map;
	}
}
