package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IFieldPlaceable.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public interface IFieldPlaceable {
	public void registerField(Field field);
	public void sell();
}
