package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IntensityGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class IntensityGem extends Gem implements IOGem {

	public static final int price = 20;

	private int intensity;
	
	public IntensityGem() {

	}
	
	public void upgradeObstacle(Obstacle o) {
		
		// sd_akadaly_fejlesztese szekvenciadiagrammon el van irva
		o.increaseIntensity(intensity);
		
	}
}
