package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IObstacle.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public interface IObstacle {
	public void slow(Enemy e);
	public void amortization();
	public void increaseIntensity(int intens);
	public void addIOGem(IOGem g);
	public void repair();
}
