package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ITower.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public interface ITower {
	public Enemy chooseEnemy();
	public void shoot();
	public void setPaths();
	public void addITGem(ITGem g);
}
