package proto;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Map.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//

public class Map {
	/**
	 * A p�lya neve.
	**/
	private String name;
	
	/**
	 * A p�lya szintje
	**/
	private int level;
	
	/**
	 * Maga a j�t�k t�rk�pe Tartalmazza a cell�kat.
	**/
	private ArrayList<ArrayList<Cell>> grid;
	
	private Game game;
	
	/**
	 * Konstruktor
	 *
	 * @param    name
	**/
	public Map(Game game) {
		ProtoTester.addToObjectCatalog(this);
	}
	
	/**
	 * Bet�lti a k�vetkez� p�ly�t.
	 *
	 * @param    name
	**/
	public void load(String name) {

	}
	
	public int getLevel() {
		return level;
	
	}
	
	public String getName() {
		return name;
	
	}
	
	public Path getFirstPath() {
		return null;
	}
	
	public Cell getCell(int i, int j){
		return grid.get(i).get(j);
	} 
}
