package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : RangeGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class RangeGem extends Gem implements ITGem {
	public static final int price = 20;

	private int range;
	public RangeGem() {

	}
	public void upgradeTower(Tower t) {
		t.upgradeRange(range);
	}
	
	public int getValue() {

		return 0;
	}
}
