package proto;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SpeedGem.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//




public class SpeedGem extends Gem implements ITGem {
	public static final int price = 20;

	private int speed;
	
	public SpeedGem() {
		ProtoTester.safePrint("--> SpeedGem konstruktor", true);
		
		ProtoTester.safePrint("<-- SpeedGem konstruktor return", false);
	}
	
	public void upgradeTower(Tower t) {
		ProtoTester.safePrint("--> SpeedGem upgradeTower", true);
		t.upgradeSpeed(speed);
		ProtoTester.safePrint("<-- SpeedGem upgradeTower return", false);
	}
	
	public int getValue() {
		return 0;
	}
}
