package proto;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tower.java
//  @ Date : 2014.03.11.
//  @ Author : itee_team
//
//


public class Tower implements ITower, IFieldPlaceable {
	/**
	 * A torony �ra. Az az �rt�k, amit a man�b�l le kell vonni ahhoz, hogy a j�t�kos megvehesse a tornyot. Statikus, mert minden toronyra ugyanaz.
	**/
	public static final int price = 10;
	
	/**
	 * A torony hat�sugara, hogy h�ny cell�t �r el a szomsz�dos cell�k k�z�l.
	**/
	private int range;
	private int speedCtr;
	private int speed;
	/**
	 * A l�ved�k amit a torony kil�.
	**/
	private Bullet bullet;
	
	/**
	 * Fejleszt�seket t�rol� v�ltoz�. Ebb�l der�l ki, hogy az adott toronyra milyen Gem-eket vett m�r meg a j�t�kos.
	**/
	private ArrayList<ITGem> gems;
	
	/**
	 * Annak a mez�nek a referenci�ja, amelyiken az adott torony �ll.
	**/
	private Field myField;
	
	/**
	 * Azon cell�k list�ja, amelyek beleesnek a l�t�vba (range).
	**/
	private ArrayList<Path> paths;
	private IGame igame;
	private Field itower;
	public Game towers;
	
	/**
	 * Konstruktor
	 *
	 * @param    rang
	 * @param    pr
	**/
	public Tower(IGame game) {
		igame = game;
		gems = new ArrayList<ITGem>();
		paths = new ArrayList<Path>();
		bullet = new Bullet();
	}
	
	public void upgradeSpeed(int sp) {
		speed += sp;
	}
	
	public void upgradeRange(int rng) {
		range += rng;
		setPaths();
	}
	
	public void upgradeEnemy(String e) {
		bullet.setEnemy(e);
	}
	
	public void upgradeDamage(int dmg) {
		bullet.setDamage(dmg);
	}
	
	public Enemy chooseEnemy() {
		Path path = paths.get(0);
		ArrayList<Enemy> enemies;
		if(!path.hasEnemy()) return null;
		enemies = path.getEnemies();
		return enemies.get(0);
	}
	
	// kivalaszt egy ellenseget es megsebzi a bullet-tel
	public void shoot() {

		Enemy target = chooseEnemy();
		if(target==null){
			return;
		}
		target.hurt(bullet);
	}
	
	// ez a fv csak teszteleshez kell
	public void addPath(Path path){
		paths.add(path);		
	}
	
	public void setPaths() {

	}
	
	public void addITGem(ITGem g) {
		g.upgradeTower(this);
		gems.add(g);
		
	}
	
	public void registerField(Field field) {
		if(!field.hasTower()){
			myField = field;
			field.registerITower(this);
		}
	}
	
	public void sell() {
		int value = price/2;
		
		
		for(ITGem g:gems){
			value = g.getValue();
		}
		
		igame.changeMana(value);
		
		igame.removeTower(this);
		
		myField.deleteIFieldPlaceable(this);
		
	}
}
